'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useDashboardRealtime } from '@/components/dashboard-realtime'

type Mode = 'live' | 'history' | 'devices' | 'alerts' | 'system'
export function DashboardDataPanel({ mode, deviceId }: { mode: Mode; deviceId?: string }) {
  const { lastEvent, stale } = useDashboardRealtime(); const [data, setData] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState<string | null>(null)
  const url = useMemo(() => mode === 'history' ? `/api/dashboard/history?bucket=1h${deviceId ? `&deviceId=${deviceId}` : ''}` : mode === 'live' ? `/api/dashboard/live?bucket=1m${deviceId ? `&deviceId=${deviceId}` : ''}` : `/api/dashboard/${mode}`, [mode, deviceId])
  const load = useCallback(async () => { try { const response = await fetch(url); const body = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(body.error || 'Unable to load dashboard data')); setData(body); setError(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load dashboard data') } }, [url])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (lastEvent?.type === 'reading.created' || lastEvent?.type.startsWith('alert.')) { const timer = window.setTimeout(() => void load(), 700); return () => window.clearTimeout(timer) } }, [lastEvent, load])
  if (error) return <div role="alert" className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-sm">{error}</div>
  if (!data) return <div className="animate-pulse rounded-lg border border-border p-6 text-sm text-muted-foreground">Loading operational data…</div>
  if (mode === 'system') return <section><h1 className="text-2xl font-semibold">System health</h1><p className="mt-1 text-sm text-muted-foreground">Direct backend/database availability and inferred telemetry health.</p><dl className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data).map(([key, value]) => <div key={key} className="rounded-lg border border-border p-4"><dt className="text-xs uppercase text-muted-foreground">{key.replaceAll(/([A-Z])/g, ' $1')}</dt><dd className="mt-2 break-words font-medium">{typeof value === 'string' || typeof value === 'number' ? String(value) : JSON.stringify(value)}</dd></div>)}</dl></section>
  if (mode === 'devices') { const docs = (data.docs || []) as Array<Record<string, unknown>>; return <section><h1 className="text-2xl font-semibold">Devices</h1><p className="mt-1 text-sm text-muted-foreground">{data.totalDocs as number} configured stations.</p><div className="mt-6 overflow-x-auto rounded-lg border border-border"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="p-3">Device</th><th className="p-3">Status</th><th className="p-3">Last seen</th><th className="p-3">Metrics</th></tr></thead><tbody>{docs.map(device => <tr key={String(device.id)} className="border-b last:border-0"><td className="p-3"><Link className="font-medium underline" href={`/dashboard/devices/${device.id}`}>{String(device.name)}</Link><br /><span className="text-xs text-muted-foreground">{String(device.deviceId)}</span></td><td className="p-3 uppercase">{String(device.status)}</td><td className="p-3">{format(device.lastSeen)}</td><td className="p-3">{metricText(device.latestMetrics)}</td></tr>)}</tbody></table></div></section> }
  if (mode === 'alerts') { const docs = (data.docs || []) as Array<Record<string, unknown>>; return <section><h1 className="text-2xl font-semibold">Alerts</h1><div className="mt-6 overflow-x-auto rounded-lg border border-border"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="p-3">Severity</th><th className="p-3">Status</th><th className="p-3">Message</th><th className="p-3">Triggered</th></tr></thead><tbody>{docs.map(alert => <tr key={String(alert.id)} className="border-b last:border-0"><td className="p-3 uppercase">{String(alert.severity)}</td><td className="p-3 uppercase">{String(alert.status)}</td><td className="p-3">{String(alert.message)}</td><td className="p-3">{format(alert.lastTriggeredAt)}</td></tr>)}</tbody></table>{!docs.length && <p className="p-6 text-sm text-muted-foreground">No alerts match the current filter.</p>}</div></section> }
  const points = (data.points || []) as Array<Record<string, unknown>>
  return <section><div className="flex flex-wrap items-end justify-between gap-2"><div><h1 className="text-2xl font-semibold">{mode === 'live' ? 'Live monitoring' : 'Historical analytics'}</h1><p className="text-sm text-muted-foreground">UTC · bounded server aggregation {stale ? '· data may be stale' : ''}</p></div><button className="rounded border px-3 py-2 text-sm" onClick={() => void load()}>Refresh</button></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Chart title="Temperature" color="#0e7490" data={points} metric="temperature" /><Chart title="Humidity" color="#2563eb" data={points} metric="humidity" /><Chart title="Pressure" color="#7c3aed" data={points} metric="pressure" /><Chart title="Latency" color="#d97706" data={points} metric="latencyMs" /></div><p className="sr-only">Charts show average values per UTC aggregation bucket. Data points: {points.length}.</p></section>
}
function Chart({ title, color, data, metric }: { title: string; color: string; data: Array<Record<string, unknown>>; metric: string }) { const chartData = data.map(point => ({ time: format(point.timestamp), value: Number((point[metric] as { average?: number } | undefined)?.average) })) ; return <article className="h-72 rounded-lg border border-border p-4"><h2 className="font-medium">{title}</h2><ResponsiveContainer width="100%" height="88%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="time" hide /><YAxis width={36} /><Tooltip /><Line type="monotone" dataKey="value" stroke={color} dot={false} /></LineChart></ResponsiveContainer></article> }
function format(value: unknown) { return typeof value === 'string' && !Number.isNaN(Date.parse(value)) ? new Date(value).toLocaleString() : 'Unavailable' }
function metricText(value: unknown) { if (!value || typeof value !== 'object') return 'Unavailable'; const metrics = value as { temperature?: number; humidity?: number; battery?: number }; return `${metrics.temperature ?? '—'} °C · ${metrics.humidity ?? '—'}% · ${metrics.battery ?? '—'}%` }
