'use client'
import { useEffect, useState } from 'react'
import { useDashboardRealtime } from '@/components/dashboard-realtime'

const presets = [{ type: 'high-temperature', label: 'Temperature warning', parameters: { targetTemperature: 36 }, durationSeconds: 60 }, { type: 'high-temperature', label: 'Temperature critical', parameters: { targetTemperature: 43 }, durationSeconds: 60 }, { type: 'high-humidity', label: 'Humidity warning', parameters: { targetHumidity: 90 }, durationSeconds: 60 }, { type: 'low-battery', label: 'Low battery', parameters: { targetBattery: 10 }, durationSeconds: 60 }, { type: 'high-latency', label: 'High latency', parameters: { delayMilliseconds: 3000 }, durationSeconds: 30 }, { type: 'pause-telemetry', label: 'Device silence', parameters: {}, durationSeconds: 45 }, { type: 'disconnect-mqtt', label: 'Temporary MQTT disconnect', parameters: {}, durationSeconds: 30 }, { type: 'reset-normal', label: 'Reset to normal', parameters: {}, durationSeconds: undefined }]
export function SimulationLab() {
  const [devices, setDevices] = useState<Array<{ id: number; deviceId: string; name: string; simulationEnabled: boolean }>>([]), [deviceId, setDeviceId] = useState(''), [message, setMessage] = useState(''); const { lastEvent } = useDashboardRealtime()
  useEffect(() => { void fetch('/api/dashboard/devices?limit=100').then(response => response.json()).then(body => { const rows = body.docs || []; setDevices(rows); if (rows[0]) setDeviceId(rows[0].deviceId) }) }, [])
  const issue = async (preset: typeof presets[number]) => { if (!deviceId || !window.confirm(`Run ${preset.label} on ${deviceId}? This is a local academic simulation.`)) return; const response = await fetch('/api/simulation/commands', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ deviceId, commandType: preset.type, durationSeconds: preset.durationSeconds, parameters: preset.parameters }) }); const body = await response.json() as { error?: string; status?: string; commandId?: string }; setMessage(response.ok ? `Command ${body.commandId} published.` : body.error || 'Command failed.') }
  return <section><h1 className="text-2xl font-semibold">Simulation Laboratory</h1><p className="mt-1 max-w-3xl text-sm text-amber-700 dark:text-amber-300">Controlled local academic simulation environment. It is disabled unless SIMULATION_LAB_ENABLED=true.</p><label className="mt-6 block max-w-md text-sm font-medium">Simulated device<select value={deviceId} onChange={event => setDeviceId(event.target.value)} className="mt-1 w-full rounded border bg-background p-2">{devices.map(device => <option key={device.id} value={device.deviceId} disabled={!device.simulationEnabled}>{device.name} ({device.deviceId}){!device.simulationEnabled ? ' — disabled' : ''}</option>)}</select></label><h2 className="mt-8 text-lg font-medium">Safe scenario presets</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{presets.map(preset => <button key={preset.label} onClick={() => void issue(preset)} className="rounded-lg border border-border p-4 text-left transition hover:bg-muted focus-visible:ring-2 focus-visible:ring-sky-500"><strong>{preset.label}</strong><span className="mt-1 block text-xs text-muted-foreground">{preset.durationSeconds ? `${preset.durationSeconds}s bounded duration` : 'Restores ordinary simulation'}</span></button>)}</div>{message && <p role="status" className="mt-4 rounded border p-3 text-sm">{message}</p>}{Boolean(lastEvent?.data.simulationCommandId) && <p className="mt-3 text-sm text-muted-foreground">Live command update: {String(lastEvent?.data.status)}</p>}</section>
}
