/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'service-accounts': ServiceAccountAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    locations: Location;
    devices: Device;
    'weather-readings': WeatherReading;
    'service-accounts': ServiceAccount;
    'alert-rules': AlertRule;
    alerts: Alert;
    'system-events': SystemEvent;
    'simulation-commands': SimulationCommand;
    'notification-preferences': NotificationPreference;
    'notification-outbox': NotificationOutbox;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    'weather-readings': WeatherReadingsSelect<false> | WeatherReadingsSelect<true>;
    'service-accounts': ServiceAccountsSelect<false> | ServiceAccountsSelect<true>;
    'alert-rules': AlertRulesSelect<false> | AlertRulesSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    'system-events': SystemEventsSelect<false> | SystemEventsSelect<true>;
    'simulation-commands': SimulationCommandsSelect<false> | SimulationCommandsSelect<true>;
    'notification-preferences': NotificationPreferencesSelect<false> | NotificationPreferencesSelect<true>;
    'notification-outbox': NotificationOutboxSelect<false> | NotificationOutboxSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | ServiceAccount;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ServiceAccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * Unique short identifier for this location (e.g. SYD, MEL, BNE).
   */
  code: string;
  city: string;
  stateOrRegion?: string | null;
  country: string;
  latitude: number;
  longitude: number;
  timezone: string;
  active?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  /**
   * Stable device identifier (e.g. WX-SYD-001). Must be unique.
   */
  deviceId: string;
  name: string;
  location: number | Location;
  status: 'online' | 'offline' | 'degraded' | 'maintenance';
  /**
   * Inactive devices are rejected by telemetry ingestion.
   */
  active: boolean;
  /**
   * Whether this device should be driven by the future device simulator.
   */
  simulationEnabled?: boolean | null;
  publishingIntervalSeconds: number;
  lastSeen?: string | null;
  firmwareVersion?: string | null;
  description?: string | null;
  /**
   * Most recent telemetry snapshot for quick reference on the device record.
   */
  latestMetrics?: {
    /**
     * Degrees Celsius.
     */
    temperature?: number | null;
    /**
     * Relative humidity percentage.
     */
    humidity?: number | null;
    /**
     * Barometric pressure in hPa.
     */
    pressure?: number | null;
    /**
     * Rainfall in millimetres.
     */
    rainfall?: number | null;
    /**
     * Wind speed in km/h.
     */
    windSpeed?: number | null;
    /**
     * Battery charge percentage.
     */
    battery?: number | null;
    recordedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-readings".
 */
export interface WeatherReading {
  id: number;
  device: number | Device;
  /**
   * Monotonically increasing per-device sequence number, used with `device` for MQTT QoS 1 duplicate protection.
   */
  sequenceNumber: number;
  temperature: number;
  humidity: number;
  pressure: number;
  rainfall: number;
  windSpeed: number;
  battery: number;
  /**
   * Timestamp reported by the device itself.
   */
  deviceTimestamp: string;
  /**
   * Timestamp the edge gateway received/forwarded the reading.
   */
  gatewayTimestamp: string;
  /**
   * Timestamp the server persisted the reading.
   */
  serverTimestamp: string;
  /**
   * End-to-end latency in milliseconds (device to server).
   */
  latencyMs: number;
  validationStatus: 'valid' | 'invalid' | 'stale' | 'duplicate';
  /**
   * Original raw payload as received, kept for debugging/audit purposes.
   */
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-accounts".
 */
export interface ServiceAccount {
  id: number;
  name: string;
  accountType: 'edge-gateway';
  active: boolean;
  description?: string | null;
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'service-accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert-rules".
 */
export interface AlertRule {
  id: number;
  name: string;
  /**
   * Stable unique rule code.
   */
  code: string;
  description?: string | null;
  enabled: boolean;
  ruleType: 'metric-threshold' | 'device-offline';
  metric?: ('temperature' | 'humidity' | 'pressure' | 'rainfall' | 'windSpeed' | 'battery' | 'latencyMs') | null;
  condition?: ('above' | 'below' | 'outside-range') | null;
  warningValue?: number | null;
  criticalValue?: number | null;
  warningMinimum?: number | null;
  warningMaximum?: number | null;
  criticalMinimum?: number | null;
  criticalMaximum?: number | null;
  offlineMultiplier?: number | null;
  minimumOfflineSeconds?: number | null;
  cooldownSeconds: number;
  autoResolve: boolean;
  scope: 'all-devices' | 'selected-locations' | 'selected-devices';
  locations?: (number | Location)[] | null;
  devices?: (number | Device)[] | null;
  messageTemplate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: number;
  device: number | Device;
  rule: number | AlertRule;
  reading?: (number | null) | WeatherReading;
  type: 'metric-threshold' | 'device-offline';
  metric?: ('temperature' | 'humidity' | 'pressure' | 'rainfall' | 'windSpeed' | 'battery' | 'latencyMs') | null;
  severity: 'warning' | 'critical';
  status: 'active' | 'acknowledged' | 'resolved';
  message: string;
  measuredValue?: number | null;
  thresholdSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurrenceCount: number;
  firstTriggeredAt: string;
  lastTriggeredAt: string;
  acknowledgedAt?: string | null;
  acknowledgedBy?: (number | null) | User;
  resolvedAt?: string | null;
  resolvedBy?: (number | null) | User;
  resolutionReason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-events".
 */
export interface SystemEvent {
  id: number;
  eventType:
    | 'alert-created'
    | 'alert-escalated'
    | 'alert-acknowledged'
    | 'alert-resolved'
    | 'device-offline'
    | 'device-recovered'
    | 'rule-created'
    | 'rule-updated'
    | 'rule-disabled'
    | 'service-account-used'
    | 'ingestion-rejected'
    | 'simulation-command-created'
    | 'simulation-command-published'
    | 'simulation-command-acknowledged'
    | 'simulation-started'
    | 'simulation-completed'
    | 'simulation-failed'
    | 'simulation-cancelled'
    | 'simulation-expired'
    | 'mqtt-device-disconnected'
    | 'mqtt-device-reconnected'
    | 'invalid-simulated-payload-rejected'
    | 'duplicate-message-ignored'
    | 'gateway-buffered-message'
    | 'gateway-buffer-flushed'
    | 'report-exported'
    | 'notification-queued'
    | 'notification-sent'
    | 'notification-retry-scheduled'
    | 'notification-failed'
    | 'notification-cancelled'
    | 'daily-digest-generated'
    | 'weekly-digest-generated'
    | 'notification-preferences-updated';
  severity: 'info' | 'warning' | 'critical';
  source: 'telemetry-ingestion' | 'alert-engine' | 'offline-worker' | 'payload-admin' | 'authentication';
  device?: (number | null) | Device;
  alert?: (number | null) | Alert;
  rule?: (number | null) | AlertRule;
  user?: (number | null) | User;
  serviceAccount?: (number | null) | ServiceAccount;
  message: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulation-commands".
 */
export interface SimulationCommand {
  id: number;
  commandId: string;
  device: number | Device;
  commandType:
    | 'high-temperature'
    | 'high-humidity'
    | 'abnormal-pressure'
    | 'low-battery'
    | 'high-latency'
    | 'pause-telemetry'
    | 'duplicate-message'
    | 'delayed-message'
    | 'out-of-order-message'
    | 'invalid-payload'
    | 'disconnect-mqtt'
    | 'reset-normal';
  status: 'queued' | 'published' | 'acknowledged' | 'running' | 'completed' | 'failed' | 'expired' | 'cancelled';
  parameters:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  durationSeconds?: number | null;
  issuedBy: number | User;
  issuedAt: string;
  expiresAt: string;
  publishedAt?: string | null;
  acknowledgedAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  failureReason?: string | null;
  alertObservedAt?: string | null;
  recoveryObservedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences".
 */
export interface NotificationPreference {
  id: number;
  user: number | User;
  emailEnabled: boolean;
  minimumSeverity: 'warning' | 'critical';
  alertCreated: boolean;
  alertEscalated: boolean;
  alertResolved: boolean;
  deviceOffline: boolean;
  deviceRecovered: boolean;
  selectedLocations?: (number | Location)[] | null;
  selectedDevices?: (number | Device)[] | null;
  allDevices: boolean;
  quietHoursEnabled: boolean;
  /**
   * 24-hour local time, HH:MM.
   */
  quietHoursStart?: string | null;
  /**
   * 24-hour local time, HH:MM.
   */
  quietHoursEnd?: string | null;
  timezone: string;
  dailyDigestEnabled: boolean;
  dailyDigestTime?: string | null;
  weeklyDigestEnabled: boolean;
  weeklyDigestDay?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday') | null;
  weeklyDigestTime?: string | null;
  includePDFReport: boolean;
  lastDailyDigestAt?: string | null;
  lastWeeklyDigestAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox".
 */
export interface NotificationOutbox {
  id: number;
  idempotencyKey: string;
  notificationType:
    | 'alert-created'
    | 'alert-escalated'
    | 'alert-resolved'
    | 'device-offline'
    | 'device-recovered'
    | 'daily-digest'
    | 'weekly-digest';
  recipientUser: number | User;
  recipientEmail: string;
  alert?: (number | null) | Alert;
  device?: (number | null) | Device;
  status: 'pending' | 'processing' | 'sent' | 'retry' | 'failed' | 'cancelled';
  subject: string;
  templateData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attemptCount: number;
  nextAttemptAt: string;
  lockedAt?: string | null;
  lockedBy?: string | null;
  sentAt?: string | null;
  providerMessageId?: string | null;
  lastErrorCategory?: string | null;
  lastErrorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'weather-readings';
        value: number | WeatherReading;
      } | null)
    | ({
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      } | null)
    | ({
        relationTo: 'alert-rules';
        value: number | AlertRule;
      } | null)
    | ({
        relationTo: 'alerts';
        value: number | Alert;
      } | null)
    | ({
        relationTo: 'system-events';
        value: number | SystemEvent;
      } | null)
    | ({
        relationTo: 'simulation-commands';
        value: number | SimulationCommand;
      } | null)
    | ({
        relationTo: 'notification-preferences';
        value: number | NotificationPreference;
      } | null)
    | ({
        relationTo: 'notification-outbox';
        value: number | NotificationOutbox;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  city?: T;
  stateOrRegion?: T;
  country?: T;
  latitude?: T;
  longitude?: T;
  timezone?: T;
  active?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  deviceId?: T;
  name?: T;
  location?: T;
  status?: T;
  active?: T;
  simulationEnabled?: T;
  publishingIntervalSeconds?: T;
  lastSeen?: T;
  firmwareVersion?: T;
  description?: T;
  latestMetrics?:
    | T
    | {
        temperature?: T;
        humidity?: T;
        pressure?: T;
        rainfall?: T;
        windSpeed?: T;
        battery?: T;
        recordedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-readings_select".
 */
export interface WeatherReadingsSelect<T extends boolean = true> {
  device?: T;
  sequenceNumber?: T;
  temperature?: T;
  humidity?: T;
  pressure?: T;
  rainfall?: T;
  windSpeed?: T;
  battery?: T;
  deviceTimestamp?: T;
  gatewayTimestamp?: T;
  serverTimestamp?: T;
  latencyMs?: T;
  validationStatus?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-accounts_select".
 */
export interface ServiceAccountsSelect<T extends boolean = true> {
  name?: T;
  accountType?: T;
  active?: T;
  description?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alert-rules_select".
 */
export interface AlertRulesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  enabled?: T;
  ruleType?: T;
  metric?: T;
  condition?: T;
  warningValue?: T;
  criticalValue?: T;
  warningMinimum?: T;
  warningMaximum?: T;
  criticalMinimum?: T;
  criticalMaximum?: T;
  offlineMultiplier?: T;
  minimumOfflineSeconds?: T;
  cooldownSeconds?: T;
  autoResolve?: T;
  scope?: T;
  locations?: T;
  devices?: T;
  messageTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  device?: T;
  rule?: T;
  reading?: T;
  type?: T;
  metric?: T;
  severity?: T;
  status?: T;
  message?: T;
  measuredValue?: T;
  thresholdSnapshot?: T;
  occurrenceCount?: T;
  firstTriggeredAt?: T;
  lastTriggeredAt?: T;
  acknowledgedAt?: T;
  acknowledgedBy?: T;
  resolvedAt?: T;
  resolvedBy?: T;
  resolutionReason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-events_select".
 */
export interface SystemEventsSelect<T extends boolean = true> {
  eventType?: T;
  severity?: T;
  source?: T;
  device?: T;
  alert?: T;
  rule?: T;
  user?: T;
  serviceAccount?: T;
  message?: T;
  metadata?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulation-commands_select".
 */
export interface SimulationCommandsSelect<T extends boolean = true> {
  commandId?: T;
  device?: T;
  commandType?: T;
  status?: T;
  parameters?: T;
  durationSeconds?: T;
  issuedBy?: T;
  issuedAt?: T;
  expiresAt?: T;
  publishedAt?: T;
  acknowledgedAt?: T;
  startedAt?: T;
  completedAt?: T;
  result?: T;
  failureReason?: T;
  alertObservedAt?: T;
  recoveryObservedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences_select".
 */
export interface NotificationPreferencesSelect<T extends boolean = true> {
  user?: T;
  emailEnabled?: T;
  minimumSeverity?: T;
  alertCreated?: T;
  alertEscalated?: T;
  alertResolved?: T;
  deviceOffline?: T;
  deviceRecovered?: T;
  selectedLocations?: T;
  selectedDevices?: T;
  allDevices?: T;
  quietHoursEnabled?: T;
  quietHoursStart?: T;
  quietHoursEnd?: T;
  timezone?: T;
  dailyDigestEnabled?: T;
  dailyDigestTime?: T;
  weeklyDigestEnabled?: T;
  weeklyDigestDay?: T;
  weeklyDigestTime?: T;
  includePDFReport?: T;
  lastDailyDigestAt?: T;
  lastWeeklyDigestAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox_select".
 */
export interface NotificationOutboxSelect<T extends boolean = true> {
  idempotencyKey?: T;
  notificationType?: T;
  recipientUser?: T;
  recipientEmail?: T;
  alert?: T;
  device?: T;
  status?: T;
  subject?: T;
  templateData?: T;
  attemptCount?: T;
  nextAttemptAt?: T;
  lockedAt?: T;
  lockedBy?: T;
  sentAt?: T;
  providerMessageId?: T;
  lastErrorCategory?: T;
  lastErrorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}